#!/bin/bash
# configure_npm.sh - Automated Nginx Proxy Manager Configuration
set -e

echo "=== Nginx Proxy Manager Configuration Script ==="
echo ""

# Check if NPM is running
if ! docker ps | grep -q "infrastructure-app-1"; then
    echo "❌ Nginx Proxy Manager is not running!"
    echo "Please start it with: docker compose -f infrastructure/nginx/docker-compose.yml up -d"
    exit 1
fi

echo "✅ Nginx Proxy Manager is running"
echo ""

# Get NPM container IP
NPM_PORT=81
NPM_URL="http://localhost:${NPM_PORT}"

echo "📋 Manual Configuration Steps:"
echo ""
echo "1. Access Nginx Proxy Manager UI:"
echo "   URL: ${NPM_URL}"
echo "   Default Email: admin@example.com"
echo "   Default Password: changeme"
echo ""
echo "2. After first login, you'll be prompted to:"
echo "   - Change your email and password"
echo "   - Update admin details"
echo ""
echo "3. Create Proxy Hosts for each domain:"
echo ""

# Domain configurations
DOMAINS=(
    "feelmagic.store|http://infrastructure-app-1:81"
    "mail.feelmagic.store|http://mailcowdockerized-nginx-mailcow-1:8080"
    "office.feelmagic.store|http://office-web-1:80"
    "ai.feelmagic.store|http://dxmt-ai-service:3000"
    "api.feelmagic.store|http://dxmt-ai-service:3000"
)

for entry in "${DOMAINS[@]}"; do
    domain="${entry%%|*}"
    target="${entry#*|}"
    echo "   📌 Domain: $domain"
    echo "      Forward Hostname/IP: ${target#http://}"
    echo "      Forward Port: (extracted from target)"
    echo "      ✅ Block Common Exploits: ON"
    echo "      ✅ Websockets Support: ON"
    echo "      ✅ Force SSL: ON"
    echo "      ✅ HTTP/2 Support: ON"
    echo "      ✅ Request Let's Encrypt SSL Certificate"
    echo "         - Email: admin@${domain}"
    echo "         - Agree to ToS: YES"
    echo ""
done

echo "4. SSL Certificates will be automatically generated by NPM"
echo ""
echo "5. After configuration, verify each domain:"
echo "   - https://feelmagic.store"
echo "   - https://mail.feelmagic.store"
echo "   - https://office.feelmagic.store"
echo "   - https://ai.feelmagic.store"
echo "   - https://api.feelmagic.store"
echo ""

# Check if we can access NPM
echo "🔍 Checking NPM accessibility..."
if curl -s -o /dev/null -w "%{http_code}" "${NPM_URL}" | grep -q "200\|301\|302"; then
    echo "✅ NPM UI is accessible at ${NPM_URL}"
    echo ""
    echo "🚀 Opening NPM in browser (if available)..."
    if command -v open &> /dev/null; then
        open "${NPM_URL}"
    elif command -v xdg-open &> /dev/null; then
        xdg-open "${NPM_URL}"
    else
        echo "Please manually open: ${NPM_URL}"
    fi
else
    echo "⚠️  NPM UI might not be ready yet. Please wait a moment and try accessing ${NPM_URL}"
fi

echo ""
echo "📝 Configuration templates are available in:"
echo "   infrastructure/nginx/templates/"
echo ""
echo "✅ Script complete. Please follow the manual steps above."
